Insert into Mechanices([FullName], [WorkExperience], [BusId])
values ('Temir', '5 years', 3)
Insert into Mechanices([FullName], [WorkExperience], [BusId])
values ('Aidana', '1 year', 2)
Insert into Mechanices([FullName], [WorkExperience], [BusId])
values ('Ivan', '3 month', 1)
Insert into Mechanices([FullName], [WorkExperience], [BusId])
values ('Vasya', '10 years', 5)
Insert into Mechanices([FullName], [WorkExperience], [BusId])
values ('RT', '1,5 years', 4)

Insert into Buses([Number], [Price], [RepairId])
values ('123asd', 1000000, 1)
Insert into Buses([Number], [Price], [RepairId])
values ('908', 4000000, 2)
Insert into Buses([Number], [Price], [RepairId])
values ('568ght', 5000000, 1)
Insert into Buses([Number], [Price], [RepairId])
values ('945tyu', 1111100, 2)
Insert into Buses([Number], [Price], [RepairId])
values ('769qwe', 3000000, 2)


Insert into Repairs([InRepair])
values (0)
Insert into Repairs([InRepair])
values (1)
